### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by ChangJoo-Park** [Jinjiang/vue-mark-display#3]
**Describe the bug**

using vue-mark-display with electron-vue

**To Reproduce**
- `npm install` and `npm run dev`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1451365/63084890-35771e80-bf87-11e9-861f-f15c33d9fa19.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jinjiang** [comment]
@ChangJoo-Park I guess it might a ES modules support issue. Because the bundle I published is exported as a ES module like:

``` js
...

export default stage;
export { setHighlighter };
```

I will find a more compatible way in the next version later. Before that, you could also try to add ES module support in your project to walk around.

Thanks.

**Comment by ChangJoo-Park** [comment]
> @ChangJoo-Park I guess it might a ES modules support issue. Because the bundle I published is exported as a ES module like:
> 
> ```js
> ...
> 
> export default stage;
> export { setHighlighter };
> ```
> 
> I will find a more compatible way in the next version later. Before that, you could also try to add ES module support in your project to walk around.
> 
> Thanks.

Thanks @Jinjiang  👍  
I'll try it.

**Comment by Jinjiang** [comment]
Fixed in `v0.2.x`. Could have a try. A little notice:

- when use it in CommonJS way, please use `require('vue-mark-display').default` and  `require('vue-mark-display').setHighlighter`
- when use it in ES Modules way, please use `import X from 'vue-mark-display'` and `import { setHighlighter } from 'vue-mark-display'`

Thanks.
